---
- name: Provisioning a new EC2 instance using Ansible playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2 instance
     amazon.aws.ec2:
        key_name: master        # Your EC2 Key Pair
        instance_type: t2.micro          # Instance type
        image: ami-0e86e20dae9224db8               # AMI ID
        region: us-east-1                 # Region
        wait: yes
        count: 1
        assign_public_ip: yes
        instance_tags:
          Name: MyJenkinsInstance
      register: ec2

    - debug:
        var: ec2




























 
